### ISSUE TITLE
Cannot find module 'lodash'

### ISSUE THREAD

**Issue by aisoncheng** [liujingbreak/atom-js-grammar#4]
i   clone from git   then move to ~/.atom/packages 

ctrl + F12 give me thie error;

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [js-func-viewer](https://github.com/liujingbreak/atom-js-grammar) package 1.1.4

### Stack Trace

Failed to activate the js-func-viewer package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-js-grammar/lib/atom-js-grammar.js:1:88)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:141:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:14.3.0 pane:close (div.title)
     -1:08.6.0 settings-view:uninstall-packages (atom-pane.pane.active)
     -1:03.7.0 application:open-folder (div.panels-item)
     -0:44.9.0 js-func-viewer:toggle (input.hidden-input)
```

### Non-Core Packages

```
js-func-viewer 1.1.4 
atom-react-autocomplete 0.1.10 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.6.10 
language-babel 2.61.0 
language-javascript-jsx 0.3.7 
node_modules undefined 
nuclide 0.223.0 
react-native-snippets 0.3.0 
react-snippets 0.7.2 
```

**Comment by liujingbreak** [comment]
Hi @aisoncheng,
If you cloned this project, you will need to run `npm install` under project directory.
